### ISSUE TITLE
Is there a way to use `bibtex-generate-autokey` or `org-ref-clean-bibtex-entry` to generate the key for a bib entry?

### ISSUE THREAD

**Issue by yangsheng6810** [org-roam/org-roam-bibtex#105]
Thanks for the nice package! It works like a charm, and solves my problem of inputting bibtex entries for a paper that I read.

By default, `org-ref` uses `bibtex-generate-autokey` to generate the key for a bib entry. For example, when downloading via `doi-utils` or `arxiv-add-bibtex-entry`. This function (or its father `org-ref-clean-bibtex-entry`) is much smarter (sanitizing symbols and accents, capitalize title, report when duplication is found, ignore meaningless words like "the", "a", "Die", etc.) and is very configurable. In order to make the keys consistent with those generated by `org-ref`, it would be much better to either reuse `org-ref-clean-bibtex-entry`, or provide some way to use `org-ref-clean-bibtex-entry` instead of `orb-autokey-generate-key`. The input for the two functions are different. One problem is that the former has no parameters, reads from around `(point), and returns nothing (`bibtex-generate-autokey` does return the key though). The latter seems to take in a union of fields, and returns a key.

**Comment by myshevchuk** [comment]
Hi, thanks for the nice words!

Currently, you cannot use another function instead of `orb-autokey-generate-key`.  However, you can set `orb-autokey-format` to an Elisp expression:

``` elisp
(setq orb-autokey-format "%e{(my-function)}"
```
This way, `orb-autokey-generate-key`'s job would be just to call your function `my-funcion`. You can then write a small wrapper for `org-ref-clean-bibtex-entry`, which should return the citation key. 

I will modify modify the code of `orb-pdf-scrapper--update-record-at-point` so that if `orb-autokey-generate-key` returns nil, the key will not be updated - it will be assumed that your function did the job. In that case, you would be able to use `org-ref-clean-bibtex-entry` directly like this:
``` elisp
(setq orb-autokey-format "%e{(org-ref-clean-bibtex-entry)}"
```

**Comment by yangsheng6810** [comment]
Thanks for the quick reply!
I didn't notice that you can set `orb-autokey-format` to use an Elisp expression! It helps a lot. There is still some glitch of using `org-ref-clean-bibtex-entry`, and I will report back with a working solution in case anyone like me have the same problem.

**Comment by myshevchuk** [comment]
Sure, glad to help! Please consider posting your solution on [Org-Roam Discord knowledge base](https://org-roam.discourse.group/) instead of GitHub. Of course, if you need some code adjustments to internal functions to make `org-ref-clean-bibtex-entry` work seamlessly, you are welcome to submit a feature request or a pull request on GitHub.
