### ISSUE TITLE
set a sub directory for bibtex notes?

### ISSUE THREAD

**Issue by cryoguy** [org-roam/org-roam-bibtex#135]
Is it possible to set a sub-directory under `org-roam-directory` for the bibtex notes, like the one for `org-roam-dailies-directory`? or simply respect the setting in `org-ref` or `helm-bibtex`.

**Comment by myshevchuk** [comment]
It's not possible to respect the settings of `org-ref` or `helm-bibtex`, because the underlying mechanism is different. However, a sub-directory can be easily set in the templates, just put the name of your subdir followed by a slash:

`(setq orb-templates 
            ...
            :file-name "sub-dir/${citekey}"
           ...)

The third time I'm kindly asking you to ask questions on [Slack](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg) or [Discourse](https://org-roam.discourse.group/) I don't have capacity to answer them here.

It's the last time I'm answering your question. Unless you file a bug report or a feature request, all your questions on GitHub will be ignored.

**Comment by cryoguy** [comment]
Thanks for the answer, and the warning. will do.  Great package! but IMHO, the README can be improved.

**Comment by myshevchuk** [comment]
Please take no offence. As the README says, the package is still alpha with all the consequences. I'm working on the manual that will cover usage in detail. By the way, the question about subdirectories has been asked and answered several times already, on Discord and Slack. These are community resources and there are a lot of users willing to help and discuss their workflows. If I don't have to answer questions that have already been answered, I'll have more time to write the manual.

**Comment by cryoguy** [comment]
@myshevchuk no worries.  You are doing a wonderful job and we appreciate it truly!
