### ISSUE TITLE
orb-edit-notes not creating new notes

### ISSUE THREAD

**Issue by Bergschrat1** [org-roam/org-roam-bibtex#167]
**Describe the bug**
Hi, I'm quite new to emacs, org-roam etc. so bear with me.
I've setup my org-ref + org-roam-bibtex following this config: https://github.com/sunnyhasija/Academic-Doom-Emacs-Config
Most things work perfectly. Just when I create a citation which doesn't have a note yet and then try to open it with the "Add notes" entry, nothing happends. No error, no warning.
When I manually create the reference not with the corresponding #+ROAM_KEY it works perfectly and the note is opened.

**To Reproduce**
1. create citation to new entry with `C-c ]` 
2. try to open notes with `org-ref-open-notes-at-point`

**Expected behavior**
I should be prompted for which orb-template I want to use. Upon selecting the template a new note should be created in my `org-ref-notes-directory`

**ORB configuration**
```elisp
(use-package! org-ref
    :after org
    :init
    ; code to run before loading org-ref
    :config
    ; code to run after loading org-ref
    )
(setq org-ref-notes-directory "~/org/roam-main/"
     ; org-ref-bibliography-notes "~/Dropbox/Org/references/articles.org" ;; not needed anymore. Notes now taken in org-roaM
      org-ref-default-bibliography '("~/Documents/papers/zotLib.bib")
      org-ref-pdf-directory "~/Zotero/storage/")

(after! org
  (add-to-list 'org-capture-templates
               '(("a"               ; key
                  "Article"         ; name
                  entry             ; type
                  (file+headline "~/org/master.org" "Article")  ; target
                  "\* %^{Title} %(org-set-tags)  :article: \n:PROPERTIES:\n:Created: %U\n:Linked: %a\n:END:\n%i\nBrief description:\n%?"  ; template
                  :prepend t        ; properties
                  :empty-lines 1    ; properties
                  :created t        ; properties
))) )

(use-package! helm-bibtex
  :after org
  :init
  ; blah blah
  :config
  ;blah blah
  )

(setq bibtex-format-citation-functions
      '((org-mode . (lambda (x) (insert (concat
                                         "\\cite{"
                                         (mapconcat 'identity x ",")
                                         "}")) ""))))
(setq
      bibtex-completion-pdf-field "file"
      bibtex-completion-bibliography '("~/Documents/papers/zotLib.bib")
      bibtex-completion-library-path '("~/Zotero/storage/")
     ; bibtex-completion-notes-path "~/Dropbox/Org/references/articles.org"  ;; not needed anymore as I take notes in org-roam
      )

(use-package! zotxt
  :after org)

(use-package! org-roam-bibtex
  :load-path "~/Documents/papers/zotLib.bib" ;Modify with your own path
  :hook (org-roam-mode . org-roam-bibtex-mode)
  :bind (:map org-mode-map
         (("C-c n a" . orb-note-actions))))
(setq orb-templates
      '(("r" "ref" plain (function org-roam-capture--get-point) ""
         :file-name "${slug}-${citekey}"
         :head "#+TITLE: ${citekey}: ${title}\n#+ROAM_KEY: ${ref}\n" ; <--
         :unnarrowed t)))
(setq orb-preformat-keywords   '(("citekey" . "=key=") "title" "url" "file" "author-or-editor" "keywords"))

(setq orb-templates
      '(("n" "ref+noter" plain (function org-roam-capture--get-point)
         ""
         :file-name "${slug}"
         :head "#+TITLE: ${citekey}: ${title}\n#+ROAM_KEY: ${ref}\n#+ROAM_TAGS:

- tags ::
- keywords :: ${keywords}
\* ${title}
:PROPERTIES:
:Custom_ID: ${citekey}
:URL: ${url}
:AUTHOR: ${author-or-editor}
:NOTER_DOCUMENT: %(orb-process-file-field \"${citekey}\")
:NOTER_PAGE:
:END:")))
```
**Environment (please complete the following information):**
 - ORB commit or MELPA package version: MELPA, not sure about the version. How do I find out?
 - Org Roam commit or MELPA package version: MELPA, not sure about the version. How do I find out?
 - Org Mode version: 9.5
 - Emacs framework: Doom
 - Emacs version: 27.1
 - OS: Linux

**Comment by myshevchuk** [comment]
Hi. I would suggest you follow the official README of this project when configuring your ORB installation. When using external resources, please also check what is written there against what is written in the README. The project is being actively developed, it is still alpha and some important features change in a breaking way, meaning that information posted in blogs or elsewhere becomes outdated very quickly.

There are a few problems with your configuration. First of all, ORB depends on Org-Roam, it does not care about `org-ref-notes-directory`. This directory is meant for Org-Ref's native note-handling mechanism. ORB looks for notes in `org-roam-directory` and in Org-Roam database.

I've seen this piece before: `:load-path "~/Documents/papers/zotLib.bib" ;Modify with your own path`. I don't know where it came from and who invented this, but it's totally wrong. `:load-path` in `use-package` is meant for loading an Emacs package, not BibTeX bibliography. `use-package` does not even know BibTeX or ORB exist!

This: `(setq orb-preformat-keywords   '(("citekey" . "=key=") "title" "url" "file" "author-or-editor" "keywords"))` must be changed to this: `(setq orb-preformat-keywords   '("citekey" "title" "url" "file" "author-or-editor" "keywords")). I was a recent breaking change, so the information in that blog post is outdated.

> Just when I create a citation which doesn't have a note yet and then try to open it with the "Add notes" entry, nothing happends. No error, no warning.
When I manually create the reference not with the corresponding #+ROAM_KEY it works perfectly and the note is opened.

Sorry, but I don't understand this because the words like "citation" and "reference" are pretty ambiguous in this situation. It would be better if you reported what you did in step by step. E.g., 1. I run `this-command`. 2. I press `this-key-sequence`. 3. I run `this-command` and so on.

I once again kindly ask you to read the README, especially the `HELP ME` section:

1. Read carefully this README file.
2. Read it once again, please.
3. Check our community resources and describe your problem there.
4. Open an issue on the bug tracker.

You ignored steps 1 through 3 and skipped immediately to step 4. I feel like my effort here is not respected, therefore I close the issue.

**Comment by Bergschrat1** [comment]
Hi, I'm very sorry. I think I got too frustrated over this and stressed out with the writing work I had to do. :sweat_smile:
Usually community resouces are the first place I aks, after I can't figure out a problem myself. I don't know why I opened a bug report for this.
Thanks for taking the time to answer me though, I appreciate it!

**Comment by myshevchuk** [comment]
Hi, no need to stress about this too :) I respond promptly on Slack. GitHub issues are reserved for bugs.
