### ISSUE TITLE
State of Org-roam v2 support?

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam-bibtex#190]
Before I release Org-roam v2, I'd like at least basic compatibility with `org-roam-bibtex`. Ideally, both packages should upgrade at the same time so MELPA upgrades aren't catastrophic. When `org-roam-bibtex` is ready, I can coordinate the upgrades of the "officially-supported" extensions to v2.

**Comment by myshevchuk** [comment]
Org-roam-bibtex as of v0.6 is fully compatible with Org-roam v2. I've switched and been using them since a month or so. There is one non-critical issue not related directly to Org-roam v2, which I was going to look at after Org-roam's v2 API has stabilized to perhaps use it to address this issue, but it doesn't prevent the upgrade. I'll look at it today and tomorrow. I may also write a few concise migration tips, although the documentation is updated, so this is not strictly necessary. There will anyway be a flow of GitHub issues, regardless of whether there are migration instructions or not - many just don't read the docs, even the README, so I don't think any of this prevents Org-roam-bibtex'  from being upgraded. You can just set the date and time and I'll merge v0.6 into `master`.

**Comment by jethrokuan** [comment]
Let's set the date to 3rd July 2021 then :smile:

**Comment by myshevchuk** [comment]
Great! I've fixed that issue and will clean up the docs by then.

**Comment by jethrokuan** [comment]
Actually let's hold this off until the v1 version of Org-roam is available in MELPA.

**Comment by myshevchuk** [comment]
Sure, when will this be? Are you going to create a separate repository?

**Comment by rberaldo** [comment]
Hi, just a quick question. If I install org-roam-bibtex now, will it support v2 by default? Thanks!

**Comment by myshevchuk** [comment]
Hi, the `master` branch is still on v0.5.x, which works only with Org-roam v1, this is also the version currently available from MELPA. To get v2 support, install from the [`org-roam-v2`](https://github.com/org-roam/org-roam-bibtex/tree/org-roam-v2) branch or a tagged commit like [v0.6.0-pre.3](https://github.com/org-roam/org-roam-bibtex/tree/v0.6.0-pre.3) manually. Tagged commits may be a few commits behind the head of `org-roam-v2` branch.

As soon as Org-roam v2 appears on MELPA, ORB `org-roam-v2` branch (v0.6+) will be merged into `master` and become available from MELPA, as a default and only option.

**Comment by rberaldo** [comment]
Awesome, I'll install from git then. Thanks for the detailed comment!

**Comment by myshevchuk** [comment]
Sure, thanks for trying ORB!

**Comment by jethrokuan** [comment]
I'm merging it now...

**Comment by rasendubi** [comment]
Hope we can merge https://github.com/org-roam/org-roam-bibtex/pull/194 in before releasing v0.6 (org-roam-bibtex breaks creating non-bibtex notes without this).

**Comment by myshevchuk** [comment]
Sorry guys, I was out of the town this weekend. Will fix the things shortly.
