### ISSUE TITLE
no such table: nodes

### ISSUE THREAD

**Issue by pawel-domanski** [org-roam/org-roam-bibtex#203]
**Describe the bug**
After start, I have that error

EmacSQL had an unhandled condition: "near line 9: no such table: nodes"

**To Reproduce**
1. Start EMacs
**Expected behavior**

**ORB configuration**
1. How the package is loaded.
(package! org-roam-bibtex
  :recipe (:host github :repo "org-roam/org-roam-bibtex"))

**Environment (please complete the following information):**
 - ORB commit or MELPA package version
latest
 - Org Roam commit or MELPA package version
latest 
- Org Mode version
 - Emacs framework [e.g. Doom, Spacemacs, Prelude, none]
Doom 
- Emacs version [e.g. 26.3, 27.1]
27.2 
- OS: [e.g. Linux, macOS, Windows]
Windows

**Comment by myshevchuk** [comment]
Hi, it seems that you are still using Org-roam v1. Could you please provide the output of calling the `org-roam-version` command?

**Comment by pawel-domanski** [comment]
1.2.3

**Comment by myshevchuk** [comment]
The master branch version of Org-roam-bibtex (v0.6+) works only with Org-roam v2. You need to upgrade Org-roam to version 2 or if you want to continue using Org-roam v1 then you should use Org-roam-bibtex v0.5. 

To upgrade Org-roam to v2 in Doom simply use the `+roam2` flag instead of `+roam`. Then the usual `doom sync && doom upgrade`. No changes to ORB are required. Note that the structure of templates are different, so be sure to read [the README](https://github.com/org-roam/org-roam-bibtex/blob/master/README.md) and [the Manual](https://github.com/org-roam/org-roam-bibtex/blob/orb-v0.5/doc/orb-manual.org).

To continue using Org-roam v1 and downgrade ORB to v0.5:

```elisp
(package! org-roam-bibtex
  :recipe (:host github :repo "org-roam/org-roam-bibtex" :branch "orb-v0.5"))
```

then quit Emacs, remove `$doomdir/.local/straight/repos/org-roam-bibtex` and `$doomdir/.local/straight/build-27.2/org-roam-bibtex`, and run `doom sync && doom upgrade`
