### ISSUE TITLE
Can org-roam-bibtex be used with an older Emacs version? (version 26.1)

### ISSUE THREAD

**Issue by sbij** [org-roam/org-roam-bibtex#205]
Hello, sorry I am no expert, but I am trying to install `org-roam-bibtex` on Debian Stable, which only has version `Emacs 26.1` in the repos, so trying to install `org-roam-bibtex` with Melpa (`M-x package-install org-roam-bibtex`) returns an error: `package-compute-transaction: Package ‘emacs-27.2’ is unavailable`. Can this package be used with an older version of Emacs?

Thanks!

Edit: i installed the package via `git clone https://github.com/org-roam/org-roam-bibtex.git` and it seems to work

**Comment by myshevchuk** [comment]
Hi, the situation is the following: ORB depends on Org-roam, which depends on Org 9.4. In vanilla Emacs, Org 9.4 is only available in version 27.2. So that's why ORB "officially" requires Emacs 27.2. Another reason is that Emacs 27.2 is the current stable version of Emacs and ORB supports only the current stable. I can't tell for sure, but both Org-roam and ORB should run fine on Emacs 26.1 with Org 9.4+ installed from an external source.
