### ISSUE TITLE
Question : how to use org-roam-bibtex 

### ISSUE THREAD

**Issue by deb75** [org-roam/org-roam-bibtex#245]
Hello,

I read `orb` manual but still do not understand clearly what is it for and how to use it.

For citation links, I use `org-ref` which `org-roam` recognizes. I can then see citation links
in org-roam user interface. With `bibtex`, it is possible to take notes about an article, book, ...
and org-roam user interface is able to check if a citation has some note attached to it or not.

Unfortunately, if citation links do appear in org-roam user interface, clicking on them does not open the file
but create an [error](https://github.com/org-roam/org-roam-ui/issues/222).

Then, what does `org` brings more ?

Regards

**Comment by myshevchuk** [comment]
Hi, 

very shortly, ORB enables expansion of Org-roam templates with BibTeX data and a few other things. For example, it provides seamless integration between bibliography managers such as Helm-bibtex, Ivy-bibtex or Citar, and Org-roam.
You can find more about ORB in several discussions on Org-roam Discourse: https://org-roam.discourse.group.

If you can do everything you want with Org-roam and plain Bibtex, then you probably don't need ORB.

I have to close this issue because this tracker is used only to track technical issues with ORB or suggest improvements. For general questions about ORB please use https://org-roam.discourse.group. For issues with Org-roam, please use the Org-roam issue tracker.
Please also consider reading our rules: https://github.com/org-roam/org-roam-bibtex#getting-help
