### ISSUE TITLE
Bind orb-note-actions

### ISSUE THREAD

**Issue by albertfgu** [org-roam/org-roam-bibtex#260]
I apologize for the basic question. The documentation says to "bind the `orb-note-actions` command to a key such as C-c n a", but I'm not sure the proper way to do this. It's hard to find example configs online, and there was one that I saw that did
```
(define-key org-roam-bibtex-mode-map (kbd "C-c n a") #'orb-note-actions)
```
However this gives me an error as the variable `org-roam-bibtex-mode-map` doesn't exist. What's the proper way to create this binding?

**Comment by myshevchuk** [comment]
There are multiple ways of doing it. If you use `use-package`, you could use its `:bind` section.  In your case, you are using a basic low-level command, which is also fine. But with most low-level commands, you need to understand a bit about what you are doing or like read a little bit more to understand. It's very easy to find good Emacs documentation online, the [Emacs](https://www.gnu.org/software/emacs/manual/html_node/emacs/index.html)  and [Elisp reference](https://www.gnu.org/software/emacs/manual/html_node/elisp/index.html) manuals being excellent starting points. Alternatively, press `C-h i` or type `M-x info` in Emacs. 

That said, you are most likely setting the key before ORB has been loaded and therefore the variable is not defined yet. However, you do not need to use `org-roam-bibtex-mode-map`, you can use any other reasonable keymap, e.g. `org-mode-map`: `(define-key org-mode-map (kbd "C-c n a") #'orb-note-actions)`

I'm closing this because I don't see any issues here.
