### ISSUE TITLE
Provide a hook that is called after note creation for userdefined extension

### ISSUE THREAD

**Issue by brianmcgillion** [org-roam/org-roam-bibtex#3]
I would specifically like to add org-noter integration on the note creation. So once the document is created, be able to call org-noter on the document which could allow it to add its NOTER_DOCUMENT stanza to the roam note. and then start a session editing notes in parallel to the document.

**Comment by Zaeph** [comment]
It's doable.  We'd need to to create a hooks to be run after `org-roam-bibtex-edit-notes`: one in case the file is created, and one in case the file already exists.  This would allow users to run functions/commands *after* the expanded template has been inserted into the buffer.

I'll hold off a little bit on adding those hooks for now, since the functions are evolving fairly rapidly.  I'll let you know once they've been added.

I'm not too sure *when* you'd want `org-roam-bibtex-edit-notes` to directly run `org-noter` upon entry, but the burden of thinking it through will be on you once the hooks are implemented. 🤡

**Comment by Zaeph** [comment]
> I'll hold off a little bit on adding those hooks for now, since the functions are evolving fairly rapidly. I'll let you know once they've been added.

PR at jethrokuan/org-roam#482.

**Comment by jethrokuan** [comment]
@brianmcgillion Is this still a req? It seems like `org-roam-bibtex` covers this use-case quite well.
