### ISSUE TITLE
`orb-preformat-keywords`

### ISSUE THREAD

**Issue by myshevchuk** [org-roam/org-roam-bibtex#38]
See discussion in #37 .

**Comment by zaeph** [comment]
Continuing the discussion here.

> But what should be expanded, `citekey` or `=key=`? How would the user know they should put `=key=` into the templates if they didn't figure it out and didn't put it in `preformat-keywords`. I'd say this user-friendliness is for users who don't bother tinkering, they see `citekey`, put `citekey` and expect the work to be done. I'd suggest to look specifically for `citekey` (make it special) in `orb-preformat-keywords` and if it's not in conc-cell than internally associate it with `=key=`.

Sorry, I wasn't clear.  For user-friendliness, I suggest we do not expose the `=key=` or any of the `=`-embraced fields to the users.  Regular users should only have to deal with strings, and we can leave the option for _power_ users to use the cons, but with the intention that they be used for regular BibTeX fields, rather than the virtual `=`-embraced which are generated by `bibtex-completion`.

**Comment by zaeph** [comment]
So, to sum up:
- We do not raise an error or a warning on the absence of `=key=`.  It's not necessary since, for file creation, we rely on the information forwarded by the `bibtex-completion` action to `orb-edit-notes`:
https://github.com/org-roam/org-roam-bibtex/blob/121182f2049e8e51823f35a53b99a11b489580b2/org-roam-bibtex.el#L419
- We add non-`=`-embraced mappings for the `=`-embraced virtual fields created by `bibtex-completion`, which are the following: `(list "=type=" "=key=" "=has-pdf=" "=has-note=")`.  So, during preformatting, we'd prepend `orb-preformat-keywords` with something like this:
```el
("=type=" . "type")
("=key=" . "citekey")
("=has-pdf=" . "pdf?")
("=has-note=" . "note?")
```
- We streamline the doc so that users are encouraged to use the `(list string…)` format, but we keep the `(list cons…)` format available for power users.

**Comment by myshevchuk** [comment]
>Sorry, I wasn't clear. For user-friendliness, I suggest we do not expose the =key= or any of the =-embraced fields to the users. Regular users should only have to deal with strings, and we can leave the option for power users to use the cons, but with the intention that they be used for regular BibTeX fields, rather than the virtual =-embraced which are generated by bibtex-completion.

Yes, this is also how I see it. But we cannot hiddenly expand the citekey because we need that variable in user templates for the expansion to happen. So the user must be aware of it to put it into their templates. What we can do, however, is set the default value of `orb-preformat-keywords` to a reasonable list of 10-15 most common field names. And second, there may actually be a situation, even  not from the user point of view, but from ours, when we do not want to automatically expand the citekey. Since we are working with prompt wildcards it may sometimes be desirable not to expand the wildcard, but to run an interactive prompt.

**Comment by zaeph** [comment]
> Yes, this is also how I see it. But we cannot hiddenly expand the citekey because we need that variable in user templates for the expansion to happen. So the user must be aware of it to put it into their templates.

Agreed, we need to make it visible in `orb-preformat-keywords`, then.

> What we can do, however, is set the default value of `orb-preformat-keywords` to a reasonable list of 10-15 most common field names.

I agree as well.  We keep the `bibtex-completion` virtual fields outside of it, and we handle those internally.  So, for instance, when `citekey` is an element of `orb-preformat-keywords`, we make it act internally as `=key=` to retrieve the citekey.



> And second, there may actually be a situation, even not from the user point of view, but from ours for further development, when we do not want to automatically expand the citekey. Since we are working with prompt wildcards it may sometimes be desirable not to expand the wildcard, but to run an interactive prompt.

I see the value in that.  So, with what I've proposed, we'd only expand `citekey` to `=key=`, then to the actual citekey when it is a member of `orb-preformat-keywords`.

**Comment by myshevchuk** [comment]
>So, to sum up:

I'd suggest we only use the list 

``` elisp
("=type=" . "type")
("=key=" . "citekey")
("=has-pdf=" . "pdf?")
("=has-note=" . "note?")
```

to check `orb-preformat-keywods` for whether it contains any of `type`, `citekey`, `pdf?` or `note?` keywords. If it does contain any of exactly these keywords but it/they are not in a cons-cell then we make it/them a cons-cell, otherwise we do not expand these keywords. So
``` elisp
(setq orb-preformat-keywords "=key="
      orb-preformat-keywords "citekey"
      orb-preformat-keywords '("citekey" . "=key"))

and probably also
     orb-preformat-keywords '("mycitekey" . "citekey")
```
are all equivalent, but
``` elisp
(setq orb-preformat-keywords nil)
```
is not.

**Comment by zaeph** [comment]
> I'd suggest we only use the list
> 
> ```emacs-lisp
> ("=type=" . "type")
> ("=key=" . "citekey")
> ("=has-pdf=" . "pdf?")
> ("=has-note=" . "note?")
> ```
> 
> to check `orb-preformat-keywods` for whether it contains any of `type`, `citekey`, `pdf?` or `note?` keywords. If it does contain any of exactly these keywords but it/they are not in a cons-cell then we make it/them a cons-cell, otherwise we do not expand these keywords. So

Got it, we're on the same page, then.  I'm drafting something up.

**Comment by zaeph** [comment]
> I'm drafting something up.

Proposal in #39.
