### ISSUE TITLE
Duplicate Ref Warnings

### ISSUE THREAD

**Issue by dangirsh** [org-roam/org-roam-bibtex#82]
I just updated to the latest `org-roam` and `org-roam-bibtex`, the rebuilt my DB.

Upon building, I see: 

> Error (org-roam): Duplicate ref Dawson_Elli_2018 in:
> 
> A: /home/dan/Sync/org-roam/Dawson_Elli_2018.org
> B: /home/dan/Sync/org-roam/Dawson_Elli_2018.org
> 
> skipping...
> Error (org-roam): Duplicate ref Li_2016 in:
> 
> A: /home/dan/Sync/org-roam/Li_2016.org
> B: /home/dan/Sync/org-roam/Li_2016.org
> 
> ...

This warning seems to be triggered by all of my ref file.s

Potentially related:  the completion for `org-roam-insert` and `org-roam-find-file` are now showing me duplicate completion entries for every file.

**Comment by zaeph** [comment]
The problem seems to be exactly what is indicated: multiple files with the same ref, i.e., `#+roam_key:` value.  The comparison doesn't look right, though.  Try to force the rebuild with `C-u M-x org-roam-build-cache`, and check if you don't have backup files in your directory, although that seems unlikely to be the problem.

**Comment by dangirsh** [comment]
I checked there are no duplicate keys with a grep. 

Reproducing this issue and the duplicate completions (which may be unrelated) seems to be hit-or-miss. I only see it if it's a clean re-build, and usually only if Emacs just started.

There are no symlinks or backup files in my directory.

**Comment by myshevchuk** [comment]
I cannot reproduce this issue with my setup. Since your configuration is unavailable, I cannot reproduce it with your setup either.

**Comment by dangirsh** [comment]
Closing as it's seemingly harmless and difficult to reproduce.

**Comment by myshevchuk** [comment]
Good, thank you. Because it's not an `org-roam-bibtex` issue definitely.
Either your setup - maybe some loading problems? Or a rare `org-roam` bug - could it possibly be that two connections to the same database are established somehow? In the best case it should be reported to `org-roam`. You can also join the Slack channel and describe your problem there.
