### ISSUE TITLE
Support with BibLatex?

### ISSUE THREAD

**Issue by jcguu95** [org-roam/org-roam-bibtex#89]
Hello,

I'm about to write a thesis, and would like to make my latex workflow and org-roam workflow as alike as possible. It seems that in latex people gradually migrate to biblatex, since it provides more flexible citing options. I'm curious if `org-roam-bibtex` does/will support that?

If that's not the case, I might confine myself to using bibtex.. Thank you!

**Comment by myshevchuk** [comment]
Hi!

`org-roam-bibtex` does not care about the BibTeX dialect, since it does not do any LaTeX/BibTeX processing. It's main task is to map BibTeX fields to `org-capture` wildcards, so that you can populate your notes with BibTeX data. On this level, there is no distinction between BibTeX and biblatex. You can use `journaltitle` field instead of `title` or `date` instead of `year`. In fact, you can use  any arbitrary field names, they do not need be supported by any of these standards. 

Shall any future features of `org-roam-bibtex` require a dialect-specific processing, biblatex will be in favour BibTeX.

If you have any concrete issue or problem with `org-roam-bibtex` in mind – like something does not work, or you want some feature implemented, please talk about it. Otherwise, I would kindly ask you to close this issue. If you want to ask questions, please visit our [Slack channel](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg) and [Discourse forum](https://org-roam.discourse.group).

**Comment by jcguu95** [comment]
Thank you for the clarification!
