### ISSUE TITLE
Can't save pdf annotaion if call org-noter from org-roam notes

### ISSUE THREAD

**Issue by pRot0ta1p** [org-roam/org-roam-bibtex#91]
Procedure to reproduce:
1. call helm-bibtex or ivy-bibtex then use the 'Edit notes' option to create a org-roam note
2. call org-noter in this note buffer, this open a pdf window
3. create a annotation ie. a highlight or a text annotation
4. save the pdf buffer and the org buffer, then quit those buffer
5. re-open the pdf file, and.... no annotation is there :rofl: , no annotation is actually saved..

 I am using the msys2 version of emacs 27.1 in a windows 10 box . Making annotation works with pdf-tools or even pdf-tool + org-noter __but without ORB__, this bug only happens when I launch org-noter from the org-roam notes buffer.

Also if I call revert-buffer after create annotation the annotation will be actually saved, next time I open the file the annotations will be where I created them.

**Comment by myshevchuk** [comment]
I was only able to reproduce the behaviour you described when the PDF file was in a symlinked directory, otherwise it works perfectly fine. With the ORB/org-noter setup suggested in the README, the BibTeX `file` field is retrieved. We do not care what you put in there 🤣.

``` sh
ln -s /directory/with/my/pdfs /symlink/to/directory/with/my/pdfs
```

``` bibtex
@article{Doe2020,
...
File = {/symlink/to/directory/with/my/pdfs/Doe2020.pdf}
...
}
```

It seems to be an issue with pdf-tools or org-noter, or whatever 😂. 

You can try one of the following (or all at once):

* Write absolute file names into your BibTeX file(s)
* Request absolute file names in `orb-templates`, e.g. `%(file-truename (orb-process-file-field \"${citekey}\"))`
* Report the issue to pdf-tools or org-noter, or both

Anyway, it has nothing to do with org-roam-bibtex 😜

**Comment by myshevchuk** [comment]
Ah, you're using Windows. They do not have symlinks, do they? Maybe something's wrong with your Windows installation.

**Comment by pRot0ta1p** [comment]
Actually windows support symlink, and I'm using it in my config.
 I think  this is a bug of org-noter, after I changed the NOTER_DOCUMENT to a symlink path, the bug occurs, and pdf-tools alone handles symblink path without any problem.
 Thanks for your help :heart:

**Comment by myshevchuk** [comment]
@pRot0ta1p The highlighting is done by pdf-tools. Org-noter just tells pdf-tools which PDF document to open reading this information from NOTER_DOCUMENT. So it must be a bug in pdf-tools, although it might as well be an intentional feature. You can try setting `directory-abbrev-alist`, it may help. And as I wrote above, telling org-roam-bibtex to convert the retrieved path to an absolute file name also works around the issue.

**Comment by pRot0ta1p** [comment]
Setting `directory-abbrev-alist' solved this bug perfectly, so maybe its just compatibility issue with emacs? Anyway to verify this I'll open issue on org-noter and pdf-tool's repo. Thanks agian.

> 
> 
> @pRot0ta1p The highlighting is done by pdf-tools. Org-noter just tells pdf-tools which PDF document to open reading this information from NOTER_DOCUMENT. So it must be a bug in pdf-tools, although it might as well be an intentional feature. You can try setting `directory-abbrev-alist`, it may help. And as I wrote above, telling org-roam-bibtex to convert the retrieved path to an absolute file name also works around the issue.
> I'm glad I could help.
